adg13_notification:
    resource: "@adg13NotificationBundle/Resources/config/routing.yml"
    prefix:   /

adg13_task:
    resource: "@adg13TaskBundle/Resources/config/routing.yml"
    prefix:   /

adg13_user:
    resource: "@adg13UserBundle/Resources/config/routing.yml"
    prefix:   /

adg13_admin:
    resource: "@adg13AdminBundle/Resources/config/routing.yml"
    prefix:   /

adg13_profile:
    resource: "@adg13ProfileBundle/Resources/config/routing.yml"
    prefix:   /