security:
    encoders:
        adg13\ProfileBundle\Entity\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity:
                class: adg13\ProfileBundle\Entity\User
                property: email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
                
        login:
            pattern:  ^/login$
            anonymous: ~

        secured_area:
            pattern:   ^/
            anonymous: ~
            form_login:
                login_path: adg13_login
                check_path: adg13_login_check
            logout:
                path:   /logout
                target: /

    access_control:
           - { path: ^/admin, roles: ROLE_ADMIN }
           - { path: ^/member, roles: ROLE_USER }
