parameters:
#    adg13_signin.example.class: adg13\SigninBundle\Example

services:
#    adg13_signin.example:
#        class: %adg13_signin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
