adg13_logout:
    pattern:     /logout    

adg13_admin_on_duty:
    pattern:    /admin/on_duty
    defaults:   { _controller: adg13AdminBundle:Admin:onDuty }
 
adg13_admin_add_member:
    pattern:    /admin/add_member
    defaults:   { _controller: adg13AdminBundle:Admin:addMember } 
    
adg13_admin_show_members:
    pattern:    /admin/show_members
    defaults:   { _controller: adg13AdminBundle:Admin:showMembers }     