parameters:
#    adg13_admin.example.class: adg13\AdminBundle\Example

services:
#    adg13_admin.example:
#        class: %adg13_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
