parameters:
#    adg13_user.example.class: adg13\UserBundle\Example

services:
#    adg13_user.example:
#        class: %adg13_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
